my_portfolio/my_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
#from django.conf.urls import url
from django.urls import re_path

urlpatterns = [
   # path('', include('portfolio_projects.urls')),
    path('admin/', admin.site.urls),
    path('', include('portfolio_projects.urls', namespace="portfolio_projects")),
    re_path(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_portfolio/portfolio_projects/urls.py
from django.urls import path
from . import views


app_name = "portfolio_projects"

urlpatterns = [
	path('', views.IndexView.as_view(), name="home"),
	path('contact/', views.ContactView.as_view(), name="contact"),
	path('portfolio/', views.PortfolioView.as_view(), name="portfolios"),
	path('portfolio/<slug:slug>', views.PortfolioDetailView.as_view(), name="portfolio"),
	path('experience/', views.WorkExperineceView.as_view(), name="experience"),
	path('experience/<slug:slug>/', views.WorkExperienceDetailView.as_view(), name="experience"),
   # path('aboutme/', views.AboutmeView.as_view(), name="aboutme"),
	]

my_portfolio/portfolio_projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField

class Technology(models.Model):
    name = models.CharField(max_length=200,blank=True,null=True)
    image = models.ImageField(blank=True,null=True)

    def __str__(self):
        return self.name
class Skill(models.Model):
    class Meta:
        verbose_name_plural = 'Skills'
        verbose_name = 'Skill'
    
    name = models.CharField(max_length=20, blank=True, null=True)
    score = models.IntegerField(default=80, blank=True, null=True)
    image = models.FileField(blank=True, null=True, upload_to="skills")
    is_key_skill = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


class ContactProfile(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'



'''class Testimonial(models.Model):

    class Meta:
        verbose_name_plural = 'Testimonials'
        verbose_name = 'Testimonial'
        ordering = ["name"]

    thumbnail = models.ImageField(blank=True, null=True, upload_to="testimonials")
    name = models.CharField(max_length=200, blank=True, null=True)
    role = models.CharField(max_length=200, blank=True, null=True)
    quote = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name'''


class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name 

class Portfolio(models.Model):

    class Meta:
        verbose_name_plural = 'Portfolio Profiles'
        verbose_name = 'Portfolio'
        ordering = ["name"]
    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    git_link = models.URLField(blank=True, null=True)
    #wlink=models.URLField(blank =True, null=True)
    #technology = models.CharField(max_length=250, blank=True)
    technology = models.ManyToManyField(Technology)
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/portfolio/{self.slug}"
    


'''class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blog Profiles'
        verbose_name = 'Blog'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}" '''


class Certificate(models.Model):

    class Meta:
        verbose_name_plural = 'Certificates'
        verbose_name = 'Certificate'

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    

'''class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    url = models.URLField()
    
    def __str__(self) :
        return self.title'''





# Create your models here.
'''class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    url = models.URLField()
    
    def __str__(self) :
        return self.title

class Skill(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name '''

class Education(models.Model):
    degree = models.CharField(max_length=100) 
    institution = models.CharField(max_length=500)
    graduation_year = models.DateField()
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return f"{self.degree} from {self.institution} ({self.graduation_year})"  
    
class Workexperience(models.Model):
    job_title = models.CharField(max_length=100)
    company = models.CharField(max_length=150)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    description = models.TextField()
    is_active = models.BooleanField(default=True)


    def __self__(self):
        return f"{self.job_title} at {self.company}"
    
'''class about(models.Model):
    description = models.CharField(max_length=500)
    resume_url = models.URLField()
    image = models.ImageField()

    def __self__(self):
        return self.description,self.resume_url,self.image'''
        


    

my_portfolio/portfolio_projects/forms.py
from django import forms
from .models import ContactProfile


class ContactForm(forms.ModelForm):

	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			'class': 'form-control'
			}))
	email = forms.EmailField(max_length=254, required=True, 
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',
			'class': 'form-control'
			}))
	message = forms.CharField(max_length=1000, required=True, 
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'class': 'form-control',
			'rows': 6,
			}))


	class Meta:
		model = ContactProfile
		fields = ('name', 'email', 'message',)

my_portfolio/portfolio_projects/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.contrib import messages
from .models import UserProfile,Portfolio,Education,Workexperience,Certificate,Technology
from .forms import ContactForm
from django.views import generic

class  IndexView(generic.TemplateView):
    template_name = "portfolio_projects/index.html"
    def get_context_data(self, **kwargs):
        #return super().get_context_data(**kwargs)
        context = super().get_context_data(**kwargs)
        certificates = Certificate.objects.filter(is_active=True)
        portfolios = Portfolio.objects.filter(is_active=True)
        education = Education.objects.filter(is_active=True)
        experience = Workexperience.objects.filter(is_active=True)
        technologies = Technology.objects.all()

        context["certificates"] = certificates
        context["portfolio"] = portfolios
        context["education"] = education
        context["experience"] = experience
        #context["technologies"] = technologies
       # print(technologies)
        return context

#class AboutmeView(generic.TemplateView):
 #   template_name = 'portfolio_projects/aboutme.html'    
    
class ContactView(generic.FormView):
    template_name = "portfolio_projects/contact.html"
    form_class = ContactForm   
    success_url= "/"

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Thank you')
        return super().form_valid(form)
    
class PortfolioView(generic.ListView):
    model = Portfolio
    template_name = "portfolio_projects/portfolio.html"
    paginate_by = 10

    def get_queryset(self) :
        return super().get_queryset().filter(is_active=True)
    
        
class PortfolioDetailView(generic.DetailView):
    model = Portfolio
    template_name = "portfolio_projects/portfolio-detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        portfolio = self.get_object()
        technologies = portfolio.technology.all()  # Fetching related technologies
        context['technologies'] = technologies
        return context


#class EducationView(generic.DetailView):
class WorkExperineceView(generic.ListView):
    model = Workexperience
    template_name = "portfolio_projects/experience.html"
    def get_queryset(self):
        print(QuerySet)
        return super().get_queryset().filter(is_active=True)

class WorkExperienceDetailView(generic.DetailView):
    model = Workexperience
    template_name = "portfolio_projects/experience-detail.html"

my_portfolio/portfolio_projects/templates/portfolio_projects/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{%endblock %}</title>
    <meta name="author" content="Designed by Anu">
    <link rel="canonical" href="{{request.path}}"/>
    <link rel="home" href="{% url 'portfolio_projects:home' %}"/>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/8665273.jpg' %}">
    <link rel="apple-touch-icon" type="image/jpg" href="{% static 'images/8665273.jpg' %}">

    <!-- ================================
    Start CSS
    ================================= -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <style>
      body {
        background-image: url('{% static "images/concrete-wall-scratched-material-background-texture-concept.jpg" %}');
        background-size: cover;
        background-repeat: no-repeat;
      }
    </style>
    {% block extend_header%}{%endblock%}
    <!-- ================================
    End CSS
    ================================= -->

  </head>
  <body>
    {% include 'portfolio_projects/partials/messages.html' %}
    {% include 'portfolio_projects/partials/nav.html' %}

    {% block content %}
    {% endblock %}

    {% include 'portfolio_projects/partials/footer.html' %}

    <!-- ================================
    Start Scripts
    ================================= -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block extend_footer %}{%endblock%}
    <!-- ================================
    End Scripts
    ================================= -->
  </body>
</html>

my_portfolio/portfolio_projects/templates/portfolio_projects/contact.html
{% extends 'portfolio_projects/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}Contact Me{% endblock %}
{% block decription %}Contact information for reaching me{% endblock %}
{% block keywords %}contact, email, phone, LinkedIn{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3 align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Contact Me</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p><strong>Email:</strong> anusree.pillai@gmail.com</p>
          <p><strong>Phone:</strong> +46 705553261</p>
          <p><strong>LinkedIn:</strong> <a href="https://www.linkedin.com/in/anu-pillai-2a5645295"> Click to Connect with Linkdin</a></p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{% endblock %}

my_portfolio/portfolio_projects/templates/portfolio_projects/index.html
{% extends 'portfolio_projects/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}
<style>
  /* Styling for the footer on the index page */
  footer.index-footer {
      display:none;
      
      left: 0;
      bottom: 0;
      width: 100%;
      
      text-align: center;
      padding: 5px 0; /* Adjust as needed */
  }
</style>
{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}
{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="bannerSection">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-auto order-md-last">
          <div class="bannerUserImg">
            <img src="{{me.userprofile.avatar.url}}" alt="{{me.first_name|title}} {{me.last_name|title}} avatar">
          </div>
        </div>
        <div class="col-md">
          <div class="bannerContent">
            <h1 class="xlTitle pb-3">Hi, I’m {{me.first_name|title}}, <br> a {{me.userprofile.title}} </br></h1>
            <p style="font-family: cursive;">{{me.userprofile.bio}}</p>
            <div class="bannerBtnCol">
              <div class="row">
                <div class="col-auto">
                  <a download href="{{me.userprofile.cv.url}}" class="btn btnPrimary">Download Resume</a>
                </div>
                <div class="col-auto">
                  <a href="{% url 'portfolio_projects:contact' %}" class="btn btnOutline">Contact</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpace pt-0">
    <div class="container">
      <div class="row">
        <div class="col-md-auto">
          <div class="keySkillCol">
            <h4 class="smTitle pb-3">Key Skills</h4>
            {% for sk in me.userprofile.skills.all %}
            {% if sk.is_key_skill %}
            <div class="keySkillCard">
              {% if sk.image %}
              <div class="ksIconCol">
                <img src="{{sk.image.url}}" alt="...">
              </div>
              {% endif %}
              <span class="ksText">{{sk.name}}</span>
            </div>
            {% endif %}
            {% endfor %}
          </div>
        </div>
        <div class="col-md">
          <h4 class="smTitle pb-3">Coding Skills</h4>
          <div class="progressCol">
            <div class="progressCard">
              {% for sk in me.userprofile.skills.all %}
              {% if not sk.is_key_skill %}
              <div class="progressCol">
                <span class="progressLbl">{{sk.name}}</span>
                <div class="row g-2 align-items-center">
                  <div class="col">
                    <div class="progress progressStyle">
                      <div class="progress-bar" role="progressbar" style="width: {{sk.score}}%" aria-valuenow="{{sk.score}}" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                  <div class="col-auto">
                    <span class="pLbl">{{sk.score}}%</span>
                  </div>
                </div>
              </div>
              {% endif %}
              {% endfor %}
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm ">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Certificates</h4>
        </div>

      </div>
      <div class="sliderOuter">
        <div class="swiper certificatesSlider">
          <div class="swiper-wrapper">
            {% for c in certificates %}
            {% if c.is_active %}
            <div class="swiper-slide">
              <div class="cardStyle1">
                <h4 class="mdTitle cs1Title">
                  <a href="javascript:void(0)">{{c.title}}</a>
                </h4>
                <ul class="cardOptionCol">
                  <li>{{c.date.date}}</li>
                  <li>{{c.name|title}}</li>
                </ul>
                <p style="font-family: cursive;">{{c.description}}</p>
              </div>
            </div>
            {% endif %}
            {% endfor %}
            
          </div>
        </div>            
        <div class="cert-swiper-button-next swiper-button-next swiperBtnStyle"></div>
        <div class="cert-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
        <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpace">
    <div class="container">
      <div class="portfolioCol">
        <div class="row pb-3">
          <div class="col">
            <h4 class="smText regular">Featured Work</h4>
          </div>
          <div class="col-auto">
            <a href="{% url 'portfolio_projects:portfolios' %}" class="simpleLink">View all</a>
          </div>
        </div>
        {% for p in portfolio %}
        {% if p.is_active %}
        <div class="portfolioCard">
          <div class="row g-4 align-items-center">
            <div class="col-md-auto">
              <div class="portfolioImgCol">
                <a href="{% url 'portfolio_projects:portfolio' slug=p.slug %}"><img src="{{p.image.url}}" alt="..."></a>
              </div>
            </div>
            <div class="col-md">
              <div class="portfolioContentCol">
                <h4 class="lgTitle"><a href="{% url 'portfolio_projects:portfolio' slug=p.slug %}">{{p.name}}</a></h4>
                <ul class="portfolioOption">
                  <li><span class="dateLbl">{{p.date.year}}</span></li>
                </ul>
                <p style="font-family: cursive;">{{p.description}}</p>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
        
      </div>
      <div class="testimonialCol">
        <h4 class="smText regular d-block">Education</h4>
        <div class="testimonialSlider">
          <div class="swiper testimonialSwiper">
            <div class="swiper-wrapper">
              {% for t in education %}
              {% if t.is_active %}
              <div class="swiper-slide">
                <div class="testimonialCard">
                  <div class="row align-items-center">
                    <div class="col-sm-auto">
                      <div class="tImgCol">
                        <img src="{% static 'images/—Pngtree—education logo_4136741.png' %}" alt="...">
                      </div>
                    </div>
                    <div class="col-sm">
                      <div class="tContentCol">
                        <h4 class="xsTitle bold">{{t.degree}} - {{t.graduation_year}}</h4>
                        <p>{{t.institution}}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endif %}
              {% endfor %}

            </div>
            <div class="test-swiper-button-next swiper-button-next swiperBtnStyle"></div>
            <div class="test-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
          </div>


        </div>
      </div>
      <!-- new-->
      <div class="testimonialCol">
        <h4 class="smText regular d-block">WorkExperience</h4>
        <div class="testimonialSlider">
          <div class="swiper testimonialSwiper">
            <div class="swiper-wrapper">
              {% for b in experience %}
              {% if b.is_active %}
              <div class="swiper-slide">
                <div class="testimonialCard">
                  <div class="row align-items-center">
                    <div class="col-sm-auto">
                      <div class="tImgCol">
                        <img src="{% static 'images/employment.png' %}" alt="...">
                      </div>
                    </div>
                    <div class="col-sm">
                      <div class="tContentCol">
                        <h4 class="xsTitle bold">{{b.job_title}} | {{b.start_date}} | {{b.end_date}}</h4>
                        <p>{{b.company}}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endif %}
              {% endfor %}

            </div>
            <div class="test-swiper-button-next swiper-button-next swiperBtnStyle"></div>
            <div class="test-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
          </div>


        </div>
      </div>
    </div>
  </div>
    </div>
  </div>
</section>

<!--
<section>
  <div class="sectionSpaceSm lightBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Work Experience</h4>
        </div>
        <div class="col-auto">
          <a href="{% url 'portfolio_projects:experience' %}" class="simpleLink"></a>
        </div>
      </div>
      <div class="row g-3">
      {% for b in experience %}
      {% if b.is_active %}
        <div class="col-lg-6">
          <div class="cardStyle1">
            <a href="{% if b.slug %}{% url 'portfolio_projects:experience' slug=b.slug %}{% else %}{% url 'portfolio_projects:experience' %}{% endif %}">
              {{ b.job_title }}
          </a>
          
          <ul class="cardOptionCol">
            <li> {{b.company}} </li>
            
          </ul>
          
            <p>{{b.description}}</p>
          </div>
        </div>
        {% endif %}
        {% endfor %}

      </div>
    </div>
  </div>
</section>-->
{% endblock %}
<!-- ================================
End Content
================================= -->
<!-- ================================
Start Footer
================================= -->
<footer class="index-footer">
  <div class="footerCol">
      <div class="container">
          <ul class="socialCol">
              <!-- Social media links -->
              <li><a href="https://github.com/anusree-pillai"><img src="{% static 'images/icons8-github-26.png' %}" alt="GitHub"></a></li>
              <li><a href="https://www.linkedin.com/in/anu-pillai-2a5645295"><img src="{% static 'images/icons8-linkedin-26.png' %}" alt="LinkedIn"></a></li>
          </ul>
          <div class="copyrightCol">
              <!-- Copyright information with a link to the designer's portfolio or website -->
              <p>Copyright ©{% now 'Y' %} All rights reserved. Designed by <a href="" target="_blank">Anu</a></p>
          </div>
      </div>
  </div>
</footer>
<!-- ================================
End Footer
================================= -->

my_portfolio/portfolio_projects/templates/portfolio_projects/portfolio.html
{% extends 'portfolio_projects/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}
<style>
    /* Ensure project images are displayed in a row */
    .swiper-container {
        width: 100%;
        height: 100%;
    }

    .swiper-slide {
        text-align: center;
        font-size: 18px;
        background: #fff;
        /* Center content vertically */
        display: flex;
        justify-content: center;
        align-items: center;
        margin-right: 10px;
        
    }

    img {

        width: 700px;
        height: 100px;
        
    }
</style>
{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">See my recent projects below</h1>
          </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="swiper-container">
          <div class="swiper-wrapper">
            {% for obj in object_list %}
            <div class="swiper-slide">
              <a href="{% url 'portfolio_projects:portfolio' slug=obj.slug %}">
                <img src="{{ obj.image.url }}" class="pImg" alt="Project Image">
              </a>
            </div>
            {% endfor %}
          </div>
          <!-- Add Pagination -->
          <div class="swiper-pagination"></div>
          <!-- Add Navigation -->
          <div class="swiper-button-next"></div>
          <div class="swiper-button-prev"></div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End Content -->
{% endblock %}

<!-- ================================
Start JavaScript blocks
================================= -->
{% block extend_footer %}
<script src="{% static 'js/swiper-bundle.min.js' %}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
    var swiper = new Swiper('.swiper-container', {
        direction: 'horizontal',
        slidesPerView: 1, // Display one slide at a time
        spaceBetween: 30, // Adjust the space between slides if needed
        loop: true,
        pagination: {
            el: '.swiper-pagination',
            clickable: true,
        },
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
    });

    // Access each slide individually
    swiper.slides.forEach(function (slide, index) {
        console.log('Slide ' + (index + 1) + ':', slide);
    });
});

</script>
{% endblock %}
<!-- ================================
END JavaScript blocks
================================= -->